Internal Server Error: /groups/import_single
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_orjson_renderer\renderers.py", line 96, in render
    serialized = orjson.dumps(
TypeError: Type is not JSON serializable: Response
Internal Server Error: /groups/import_single
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 204, in _get_response
    response = response.render()
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\template\response.py", line 105, in render
    self.content = self.rendered_content
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\response.py", line 70, in rendered_content
    ret = renderer.render(self.data, accepted_media_type, context)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_orjson_renderer\renderers.py", line 96, in render
    serialized = orjson.dumps(
TypeError: Type is not JSON serializable: Response
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'POST, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '35')}[0m
[35mb'{"message":"Incorrect data format"}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'POST, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '35')}[0m
[35mb'{"message":"Incorrect data format"}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'POST, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '35')}[0m
[35mb'{"message":"Incorrect data format"}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'POST, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '35')}[0m
[35mb'{"message":"Incorrect data format"}'[0m
Internal Server Error: /groups/import_single
Traceback (most recent call last):
  File "C:\Projects\booking-api-django\groups\serializers.py", line 262, in create
    if validate_phone_number(chunk.decode('utf8').split(';')[2]):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\groups\views.py", line 129, in post
    group = serializer.save()
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "C:\Projects\booking-api-django\groups\serializers.py", line 280, in create
    "full_name": chunk.decode('cp1251').encode('utf-8').split(';')[0],
TypeError: a bytes-like object is required, not 'str'
Internal Server Error: /groups/import_single
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\groups\views.py", line 129, in post
    group = serializer.save()
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "C:\Projects\booking-api-django\groups\serializers.py", line 262, in create
    if validate_phone_number(chunk.split(';')[2]):
TypeError: a bytes-like object is required, not 'str'
Internal Server Error: /groups/import_single
Traceback (most recent call last):
  File "C:\Projects\booking-api-django\groups\serializers.py", line 262, in create
    if validate_phone_number(chunk.decode('utf8').split(';')[2]):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\groups\views.py", line 129, in post
    group = serializer.save()
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "C:\Projects\booking-api-django\groups\serializers.py", line 279, in create
    print("full_name", chunk.decode('cp1252').split(';')[0])
  File "C:\Users\AngryNerd\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 15, in decode
    return codecs.charmap_decode(input,errors,decoding_table)
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 14: character maps to <undefined>
Internal Server Error: /groups/import_single
Traceback (most recent call last):
  File "C:\Projects\booking-api-django\groups\serializers.py", line 262, in create
    if validate_phone_number(chunk.decode('utf8').split(';')[2]):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\groups\views.py", line 129, in post
    group = serializer.save()
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "C:\Projects\booking-api-django\groups\serializers.py", line 279, in create
    print("full_name", chunk.decode('utf8').split(';')[0])
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 0: invalid start byte
Internal Server Error: /groups/import_single
Traceback (most recent call last):
  File "C:\Projects\booking-api-django\groups\serializers.py", line 262, in create
    if validate_phone_number(chunk.decode('utf8').split(';')[2]):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\groups\views.py", line 129, in post
    group = serializer.save()
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "C:\Projects\booking-api-django\groups\serializers.py", line 279, in create
    print("full_name", chunk.decode('cp-1251').split(';')[0])
LookupError: unknown encoding: cp-1251
Internal Server Error: /groups/import_single
Traceback (most recent call last):
  File "C:\Projects\booking-api-django\groups\serializers.py", line 262, in create
    if validate_phone_number(chunk.decode('utf8').split(';')[2]):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\groups\views.py", line 129, in post
    group = serializer.save()
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "C:\Projects\booking-api-django\groups\serializers.py", line 279, in create
    print("full_name", chunk.decode('cp-1251').split(';')[0])
LookupError: unknown encoding: cp-1251
Internal Server Error: /groups/import_single
Traceback (most recent call last):
  File "C:\Projects\booking-api-django\groups\serializers.py", line 262, in create
    if validate_phone_number(chunk.decode('utf8').split(';')[2]):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 0: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\groups\views.py", line 129, in post
    group = serializer.save()
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "C:\Projects\booking-api-django\groups\serializers.py", line 279, in create
    print("full_name", chunk.decode('cp1251').split(';')[0])
LookupError: unknown encoding: cp-1251
Internal Server Error: /groups/import_list
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\groups\views.py", line 115, in post
    groups = serializer.save()
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "C:\Projects\booking-api-django\groups\serializers.py", line 138, in create
    list_of_group_titles.append(chunk.decode('utf8').split(',')[1])
IndexError: list index out of range
Internal Server Error: /groups/import_list
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\groups\views.py", line 115, in post
    groups = serializer.save()
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "C:\Projects\booking-api-django\groups\serializers.py", line 138, in create
    list_of_group_titles.append(chunk.decode('utf8').split(',')[1])
IndexError: list index out of range
Internal Server Error: /groups/import_list
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\groups\views.py", line 115, in post
    groups = serializer.save()
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "C:\Projects\booking-api-django\groups\serializers.py", line 138, in create
    list_of_group_titles.append(chunk.decode('utf8').split(',')[1])
IndexError: list index out of range
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, DELETE, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '49')}[0m
[35mb'{"message":"Table already booked for this date."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, DELETE, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '49')}[0m
[35mb'{"message":"Table already booked for this date."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, DELETE, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '49')}[0m
[35mb'{"message":"Table already booked for this date."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, DELETE, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '49')}[0m
[35mb'{"message":"Table already booked for this date."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, DELETE, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '49')}[0m
[35mb'{"message":"Table already booked for this date."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, DELETE, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '55')}[0m
[35mb'{"message":"User already has a booking for this date."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, DELETE, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '55')}[0m
[35mb'{"message":"User already has a booking for this date."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, DELETE, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '55')}[0m
[35mb'{"message":"User already has a booking for this date."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, POST, DELETE, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '55')}[0m
[35mb'{"message":"User already has a booking for this date."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'www-authenticate': ('WWW-Authenticate', 'Bearer realm="api"'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '58')}[0m
[35mb'{"detail":"Authentication credentials were not provided."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '267')}[0m
[35mb'{"date_from":["Date has wrong format. Use one of these formats instead: YYYY-MM-DD."],"date_to":["Date has wrong format. Use one of these formats instead: YYYY-MM-DD."],"message":"Date has wrong format. Use one of these formats instead: YYYY-MM-DD.","code":"invalid"}'[0m
Internal Server Error: /book/room_type_stats
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\win32com\client\dynamic.py", line 81, in _GetGoodDispatch
    IDispatch = pythoncom.connect(IDispatch)
pywintypes.com_error: (-2147221008, '�� ��� ���������� ����� CoInitialize.', None, None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\bookings\views.py", line 342, in get
    xlApp = client.Dispatch("Excel.Application")
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\win32com\client\__init__.py", line 95, in Dispatch
    dispatch, userName = dynamic._GetGoodDispatchAndUserName(dispatch,userName,clsctx)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\win32com\client\dynamic.py", line 98, in _GetGoodDispatchAndUserName
    return (_GetGoodDispatch(IDispatch, clsctx), userName)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\win32com\client\dynamic.py", line 83, in _GetGoodDispatch
    IDispatch = pythoncom.CoCreateInstance(IDispatch, None, clsctx, pythoncom.IID_IDispatch)
pywintypes.com_error: (-2147221008, '�� ��� ���������� ����� CoInitialize.', None, None)
Internal Server Error: /book/room_type_stats
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\pdfkit\configuration.py", line 21, in __init__
    with open(self.wkhtmltopdf) as f:
FileNotFoundError: [Errno 2] No such file or directory: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\bookings\views.py", line 429, in get
    pdfkit.from_file(Path(str(Path.cwd()) + "/" + secure_file_name.replace('.xlsx', '.html')),
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\pdfkit\api.py", line 46, in from_file
    r = PDFKit(input, 'file', options=options, toc=toc, cover=cover, css=css,
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\pdfkit\pdfkit.py", line 42, in __init__
    self.configuration = (Configuration() if configuration is None
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\pdfkit\configuration.py", line 24, in __init__
    raise IOError('No wkhtmltopdf executable found: "%s"\n'
OSError: No wkhtmltopdf executable found: "b''"
If this file exists please check that this process can read it. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf
Internal Server Error: /book/room_type_stats
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\pdfkit\configuration.py", line 21, in __init__
    with open(self.wkhtmltopdf) as f:
FileNotFoundError: [Errno 2] No such file or directory: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\bookings\views.py", line 429, in get
    pdfkit.from_file(Path(str(Path.cwd()) + "/" + secure_file_name.replace('.xlsx', '.html')),
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\pdfkit\api.py", line 46, in from_file
    r = PDFKit(input, 'file', options=options, toc=toc, cover=cover, css=css,
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\pdfkit\pdfkit.py", line 42, in __init__
    self.configuration = (Configuration() if configuration is None
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\pdfkit\configuration.py", line 24, in __init__
    raise IOError('No wkhtmltopdf executable found: "%s"\n'
OSError: No wkhtmltopdf executable found: "b''"
If this file exists please check that this process can read it. Otherwise please install wkhtmltopdf - https://github.com/JazzCore/python-pdfkit/wiki/Installing-wkhtmltopdf
Internal Server Error: /book/room_type_stats
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\bookings\views.py", line 429, in get
    pdfkit.from_file(Path(str(Path.cwd()) + "/" + secure_file_name.replace('.xlsx', '.html')),
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\pdfkit\api.py", line 49, in from_file
    return r.to_pdf(output_path)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\pdfkit\pdfkit.py", line 126, in to_pdf
    args = self.command(path)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\pdfkit\pdfkit.py", line 123, in command
    return list(self._command(path))
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\pdfkit\pdfkit.py", line 112, in _command
    for s in self.source.source:
TypeError: 'WindowsPath' object is not iterable
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
Internal Server Error: /book/future
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\bookings\views.py", line 648, in get
    date_validation(serializer.data.get('date'))
  File "C:\Projects\booking-api-django\bookings\serializers.py", line 506, in date_validation
    datetime.strptime(date, '%Y-%m-%d')
TypeError: strptime() argument 1 must be str, not None
Internal Server Error: /book/room_type_stats
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\bookings\views.py", line 435, in get
    response_dict = orjson.loads(response.text)
UnboundLocalError: local variable 'response' referenced before assignment
Internal Server Error: /book/room_type_stats
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\bookings\views.py", line 435, in get
    response_dict = orjson.loads(response.text)
UnboundLocalError: local variable 'response' referenced before assignment
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
Internal Server Error: /book/room_type_stats
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\bookings\views.py", line 444, in get
    Path(str(Path.cwd()) + "/" + secure_file_name.replace('.xlsx', '.pdf')).stat().st_size,
  File "C:\Users\AngryNerd\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1221, in stat
    return self._accessor.stat(self)
FileNotFoundError: [WinError 2] �� ������� ����� ��������� ����: 'C:\\Projects\\booking-api-django\\bed6fb3ba27641d38e032d41625c0093From_2020-01-01_To_2020-12-12.pdf'
Internal Server Error: /book/room_type_stats
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\bookings\views.py", line 444, in get
    Path(str(Path.cwd()) + "/" + secure_file_name.replace('.xlsx', '.pdf')).stat().st_size,
  File "C:\Users\AngryNerd\AppData\Local\Programs\Python\Python39\lib\pathlib.py", line 1221, in stat
    return self._accessor.stat(self)
FileNotFoundError: [WinError 2] �� ������� ����� ��������� ����: 'C:\\Projects\\booking-api-django\\3900403658844d70a922bf5467431aceFrom_2020-01-01_To_2020-12-12.pdf'
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
Internal Server Error: /book/room_type_stats
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\bookings\views.py", line 438, in get
    response_dict = orjson.loads(response.text)
UnboundLocalError: local variable 'response' referenced before assignment
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
Internal Server Error: /book/room_type_stats
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\bookings\views.py", line 438, in get
    response_dict = orjson.loads(response.text)
UnboundLocalError: local variable 'response' referenced before assignment
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '23')}[0m
[35mb'{"detail":"Not found."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'www-authenticate': ('WWW-Authenticate', 'Bearer realm="api"'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '183')}[0m
[35mb'{"detail":"Given token not valid for any token type","code":"token_not_valid","messages":[{"token_class":"AccessToken","token_type":"access","message":"Token is invalid or expired"}]}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'www-authenticate': ('WWW-Authenticate', 'Bearer realm="api"'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '183')}[0m
[35mb'{"detail":"Given token not valid for any token type","code":"token_not_valid","messages":[{"token_class":"AccessToken","token_type":"access","message":"Token is invalid or expired"}]}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '267')}[0m
[35mb'{"date_from":["Date has wrong format. Use one of these formats instead: YYYY-MM-DD."],"date_to":["Date has wrong format. Use one of these formats instead: YYYY-MM-DD."],"message":"Date has wrong format. Use one of these formats instead: YYYY-MM-DD.","code":"invalid"}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'POST, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '40')}[0m
[35mb'{"detail":"Incorrect email or password"}'[0m
Internal Server Error: /book/employee_stats
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\bookings\views.py", line 481, in get
    month_num = int(strptime(month, '%B').tm_mon)
  File "C:\Users\AngryNerd\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "C:\Users\AngryNerd\AppData\Local\Programs\Python\Python39\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '03' does not match format '%B'
Internal Server Error: /book/employee_stats
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\bookings\views.py", line 598, in get
    worksheet.write('B' + str(i), list_rows[j]['phone_number'])
KeyError: 'phone_number'
Internal Server Error: /book/future
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\bookings\views.py", line 683, in get
    sql_results.append(bookings_future(s))
  File "C:\Projects\booking-api-django\bookings\serializers.py", line 484, in bookings_future
    "phone_number": str(stats.phone_number),
AttributeError: 'Booking' object has no attribute 'phone_number'
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, PUT, DELETE, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '111')}[0m
[35mb'{"detail":["Group with this title already exists"],"message":"Group with this title already exists","code":400}'[0m
Internal Server Error: /book
Traceback (most recent call last):
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/bookings/views.py", line 84, in post
    serializer.save()
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 205, in save
    self.instance = self.create(validated_data)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/bookings/serializers.py", line 136, in create
    message=f"Было совершено бронирование капсулы сна пользователем {validated_data['user'].user.phone_number} "
TypeError: 'datetime.datetime' object is not subscriptable
Internal Server Error: /office
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\offices\views.py", line 52, in get
    return Response(TestOfficeBaseSerializer(instance=office), status=status.HTTP_200_OK)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\response.py", line 38, in __init__
    raise AssertionError(msg)
AssertionError: You passed a Serializer instance as data, but probably meant to pass serialized `.data` or `.error`. representation.
Internal Server Error: /office
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'License' object has no attribute 'expires_status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\offices\views.py", line 52, in get
    return Response(TestOfficeBaseSerializer(instance=office).data, status=status.HTTP_200_OK)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 548, in data
    ret = super().data
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "C:\Projects\booking-api-django\offices\serializers.py", line 69, in to_representation
    response = super(TestOfficeBaseSerializer, self).to_representation(instance)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\fields.py", line 490, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `expires_status` on serializer `TestLicenseSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `License` instance.
Original exception text was: 'License' object has no attribute 'expires_status'.
Internal Server Error: /office
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'License' object has no attribute 'expiry_status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\offices\views.py", line 52, in get
    return Response(TestOfficeBaseSerializer(instance=office).data, status=status.HTTP_200_OK)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 548, in data
    ret = super().data
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "C:\Projects\booking-api-django\offices\serializers.py", line 69, in to_representation
    response = super(TestOfficeBaseSerializer, self).to_representation(instance)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\fields.py", line 490, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `expiry_status` on serializer `TestLicenseSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `License` instance.
Original exception text was: 'License' object has no attribute 'expiry_status'.
Internal Server Error: /office
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'License' object has no attribute 'expiry_status'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\booking-api-django\offices\views.py", line 52, in get
    return Response(TestOfficeBaseSerializer(instance=office).data, status=status.HTTP_200_OK)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 548, in data
    ret = super().data
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "C:\Projects\booking-api-django\offices\serializers.py", line 69, in to_representation
    response = super(TestOfficeBaseSerializer, self).to_representation(instance)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 515, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\fields.py", line 490, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `expiry_status` on serializer `TestLicenseSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `License` instance.
Original exception text was: 'License' object has no attribute 'expiry_status'.
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'www-authenticate': ('WWW-Authenticate', 'Bearer realm="api"'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, PUT, DELETE, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '58')}[0m
[35mb'{"detail":"Authentication credentials were not provided."}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'POST, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '33')}[0m
[35mb'{"message":"Invalid Credentials"}'[0m
Internal Server Error: /swagger/
Traceback (most recent call last):
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_yasg\views.py", line 94, in get
    schema = generator.get_schema(request, self.public)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_yasg\generators.py", line 246, in get_schema
    paths, prefix = self.get_paths(endpoints, components, request, public)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_yasg\generators.py", line 404, in get_paths
    operation = self.get_operation(view, path, prefix, method, components, request)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_yasg\generators.py", line 446, in get_operation
    operation = view_inspector.get_operation(operation_keys)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_yasg\inspectors\view.py", line 32, in get_operation
    body = self.get_request_body_parameters(consumes)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_yasg\inspectors\view.py", line 85, in get_request_body_parameters
    schema = self.get_request_body_schema(serializer)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_yasg\inspectors\view.py", line 142, in get_request_body_schema
    return self.serializer_to_schema(serializer)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_yasg\inspectors\base.py", line 437, in serializer_to_schema
    return self.probe_inspectors(
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_yasg\inspectors\field.py", line 33, in get_schema
    return self.probe_field_inspectors(serializer, openapi.Schema, self.use_definitions)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_yasg\inspectors\base.py", line 228, in probe_field_inspectors
    return self.probe_inspectors(
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_yasg\inspectors\base.py", line 110, in probe_inspectors
    result = method(obj, **kwargs)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_yasg\inspectors\field.py", line 124, in field_to_swagger_object
    actual_schema = definitions.setdefault(ref_name, make_schema_definition)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_yasg\openapi.py", line 688, in setdefault
    ret = maker()
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\drf_yasg\inspectors\field.py", line 93, in make_schema_definition
    for property_name, child in serializer.fields.items():
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 349, in fields
    for key, value in self.get_fields().items():
  File "C:\Projects\pythonProject\booking-api-django\venv\lib\site-packages\rest_framework\serializers.py", line 1004, in get_fields
    assert hasattr(self, 'Meta'), (
AssertionError: Class LoginOfficePanel missing "Meta" attribute
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'POST, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '156')}[0m
[35mb'{"slots":[{"non_field_errors":["Cannot create booking in the past"]}],"non_field_errors":[{"message":"Cannot create booking in the past","code":"invalid"}]}'[0m
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'POST, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '45')}[0m
[35mb'{"message":"User already exist","code":"400"}'[0m
Internal Server Error: /panel/book/slots
Traceback (most recent call last):
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 457, in get_attribute
    return get_attribute(instance, self.source_attrs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 97, in get_attribute
    instance = getattr(instance, attr)
AttributeError: 'list' object has no attribute 'slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/bookings/views.py", line 252, in post
    return Response(serializer.data, status=status.HTTP_200_OK)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 548, in data
    ret = super().data
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 246, in data
    self._data = self.to_representation(self.instance)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/serializers.py", line 502, in to_representation
    attribute = field.get_attribute(instance)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/fields.py", line 490, in get_attribute
    raise type(exc)(msg)
AttributeError: Got AttributeError when attempting to get a value for field `slots` on serializer `BookingSlotsSerializer`.
The serializer field might be named incorrectly and not match any attribute or key on the `list` instance.
Original exception text was: 'list' object has no attribute 'slots'.
Internal Server Error: /panel/book/from_panel
Traceback (most recent call last):
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InvalidColumnReference: SELECT DISTINCT ON expressions must match initial ORDER BY expressions
LINE 1: SELECT DISTINCT ON ("bookings_booking"."id") "bookings_booki...
                            ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/bookings/views.py", line 102, in post
    for response in bookings_for_response:
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: SELECT DISTINCT ON expressions must match initial ORDER BY expressions
LINE 1: SELECT DISTINCT ON ("bookings_booking"."id") "bookings_booki...
                            ^

[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
Internal Server Error: /panel/book/from_panel
Traceback (most recent call last):
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/bookings/views.py", line 112, in post
    response_to_panel = sorted(response_to_panel, key=itemgetter(1))
KeyError: 1
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
[35m{'content-type': ('Content-Type', 'application/json'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '44'), 'vary': ('Vary', 'Origin')}[0m
[35mb'{"status_code": 404, "message": "Not found"}'[0m
Internal Server Error: /panel/book/from_panel
Traceback (most recent call last):
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InvalidColumnReference: SELECT DISTINCT ON expressions must match initial ORDER BY expressions
LINE 1: SELECT DISTINCT ON ("bookings_booking"."id") "bookings_booki...
                            ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/bookings/views.py", line 104, in post
    for response in bookings_for_response:
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: SELECT DISTINCT ON expressions must match initial ORDER BY expressions
LINE 1: SELECT DISTINCT ON ("bookings_booking"."id") "bookings_booki...
                            ^

Internal Server Error: /panel/book/from_panel
Traceback (most recent call last):
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InvalidColumnReference: SELECT DISTINCT ON expressions must match initial ORDER BY expressions
LINE 1: SELECT DISTINCT ON ("bookings_booking"."id") "bookings_booki...
                            ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/bookings/views.py", line 104, in post
    for response in bookings_for_response:
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: SELECT DISTINCT ON expressions must match initial ORDER BY expressions
LINE 1: SELECT DISTINCT ON ("bookings_booking"."id") "bookings_booki...
                            ^

Internal Server Error: /panel/book/from_panel
Traceback (most recent call last):
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.InvalidColumnReference: SELECT DISTINCT ON expressions must match initial ORDER BY expressions
LINE 1: SELECT DISTINCT ON ("bookings_booking"."id") "bookings_booki...
                            ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/bookings/views.py", line 105, in post
    for response in bookings_for_response:
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/models/query.py", line 287, in __iter__
    self._fetch_all()
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/crowiant/Desktop/Master CORS/TempDjango/booking-api-django/venv/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: SELECT DISTINCT ON expressions must match initial ORDER BY expressions
LINE 1: SELECT DISTINCT ON ("bookings_booking"."id") "bookings_booki...
                            ^

[27/May/2021 13:58:29,220] [31m[0m
[27/May/2021 13:58:29,220] [31mRequest on GET /admin/booking/employee_stats ended with code: 401[0m
[27/May/2021 13:58:29,220] [31mUser: Anonymous User[0m
[27/May/2021 13:58:29,221] [31mRequest details:[0m
[27/May/2021 13:58:29,221] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.0', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'dd80a3ab-aa85-49c4-be29-69429e382913', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[27/May/2021 13:58:29,222] [31mResponse details:[0m
[27/May/2021 13:58:29,222] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'www-authenticate': ('WWW-Authenticate', 'Bearer realm="api"'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '183')}[0m
[27/May/2021 13:58:29,222] [31m{"detail":"Given token not valid for any token type","code":"token_not_valid","messages":[{"token_class":"AccessToken","token_type":"access","message":"Token is invalid or expired"}]}[0m
[27/May/2021 13:58:38,228] [31m[0m
[27/May/2021 13:58:38,228] [31mRequest on GET /admin/booking/employee_stats ended with code: 401[0m
[27/May/2021 13:58:38,228] [31mUser: Anonymous User[0m
[27/May/2021 13:58:38,229] [31mRequest details:[0m
[27/May/2021 13:58:38,229] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.0', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '9784fc4e-59c5-49b9-b560-e04b18597f88', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[27/May/2021 13:58:38,229] [31mResponse details:[0m
[27/May/2021 13:58:38,229] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'www-authenticate': ('WWW-Authenticate', 'Bearer realm="api"'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '183')}[0m
[27/May/2021 13:58:38,229] [31m{"detail":"Given token not valid for any token type","code":"token_not_valid","messages":[{"token_class":"AccessToken","token_type":"access","message":"Token is invalid or expired"}]}[0m
[27/May/2021 13:58:56,467] [35;1m[35;1mInternal Server Error: /admin/booking/employee_stats[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/bookings/views_admin.py", line 72, in get
    response = serializer.get_statistic()
  File "/home/p7chkn/Dev/booking-api-django/bookings/serializers_admin.py", line 371, in get_statistic
    if len(self.data.get('month')) > 10 or \
TypeError: object of type 'NoneType' has no len()
[27/May/2021 13:58:56,470] [31m[0m
[27/May/2021 13:58:56,470] [31mRequest on GET /admin/booking/employee_stats ended with code: 500[0m
[27/May/2021 13:58:56,470] [31mUser: fe87620c-5e80-4a1c-9c30-c4681387483a, Account: 7689fea5-32e6-4b36-a353-e152e8eb814d[0m
[27/May/2021 13:58:56,470] [31mRequest details:[0m
[27/May/2021 13:58:56,470] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.0', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '97ff9a8f-283c-4179-8063-741cf7a74fdf', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[27/May/2021 13:58:56,470] [31mResponse details:[0m
[27/May/2021 13:58:56,471] [31mUsed tables: groups_group, users_account, users_account_groups, users_user[0m
[27/May/2021 13:59:59,767] [35;1m[35;1mInternal Server Error: /admin/booking/employee_stats[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/bookings/views_admin.py", line 72, in get
    response = serializer.get_statistic()
  File "/home/p7chkn/Dev/booking-api-django/bookings/serializers_admin.py", line 372, in get_statistic
    int(self.data.get('year')) not in range(1970, 2500):
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
[27/May/2021 13:59:59,767] [31m[0m
[27/May/2021 13:59:59,768] [31mRequest on GET /admin/booking/employee_stats?month=1 ended with code: 500[0m
[27/May/2021 13:59:59,768] [31mUser: fe87620c-5e80-4a1c-9c30-c4681387483a, Account: 7689fea5-32e6-4b36-a353-e152e8eb814d[0m
[27/May/2021 13:59:59,768] [31mRequest details:[0m
[27/May/2021 13:59:59,768] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.0', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'cc6e6b07-d585-4ea4-83fd-4d7a07ec18c5', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[27/May/2021 13:59:59,769] [31mResponse details:[0m
[27/May/2021 13:59:59,769] [31mUsed tables: groups_group, users_account, users_account_groups, users_user[0m
[27/May/2021 14:01:13,890] [35;1m[35;1mInternal Server Error: /admin/booking/employee_stats[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/bookings/views_admin.py", line 72, in get
    response = serializer.get_statistic()
  File "/home/p7chkn/Dev/booking-api-django/bookings/serializers_admin.py", line 376, in get_statistic
    month_num = int(strptime(month, '%B').tm_mon)
  File "/usr/lib/python3.8/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '1' does not match format '%B'
[27/May/2021 14:01:13,893] [31m[0m
[27/May/2021 14:01:13,893] [31mRequest on GET /admin/booking/employee_stats?month=1&year=2001 ended with code: 500[0m
[27/May/2021 14:01:13,893] [31mUser: fe87620c-5e80-4a1c-9c30-c4681387483a, Account: 7689fea5-32e6-4b36-a353-e152e8eb814d[0m
[27/May/2021 14:01:13,893] [31mRequest details:[0m
[27/May/2021 14:01:13,893] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.0', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '564b1fe8-7d76-4ca2-83af-21997766cc50', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[27/May/2021 14:01:13,894] [31mResponse details:[0m
[27/May/2021 14:01:13,894] [31mUsed tables: groups_group, users_account, users_account_groups, users_user[0m
[27/May/2021 14:03:24,226] [35;1m[35;1mInternal Server Error: /admin/booking/employee_stats[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/bookings/views_admin.py", line 72, in get
    response = serializer.get_statistic()
  File "/home/p7chkn/Dev/booking-api-django/bookings/serializers_admin.py", line 376, in get_statistic
    month_num = int(strptime(month, '%B').tm_mon)
  File "/usr/lib/python3.8/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data 'NOV' does not match format '%B'
[27/May/2021 14:03:24,227] [31m[0m
[27/May/2021 14:03:24,227] [31mRequest on GET /admin/booking/employee_stats?month=NOV&year=2001 ended with code: 500[0m
[27/May/2021 14:03:24,228] [31mUser: fe87620c-5e80-4a1c-9c30-c4681387483a, Account: 7689fea5-32e6-4b36-a353-e152e8eb814d[0m
[27/May/2021 14:03:24,228] [31mRequest details:[0m
[27/May/2021 14:03:24,229] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.0', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '2c1084e4-5812-4275-b422-1addbcf11e40', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[27/May/2021 14:03:24,229] [31mResponse details:[0m
[27/May/2021 14:03:24,229] [31mUsed tables: groups_group, users_account, users_account_groups, users_user[0m
[27/May/2021 14:03:28,759] [35;1m[35;1mInternal Server Error: /admin/booking/employee_stats[0m[0m
Traceback (most recent call last):
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/home/p7chkn/Dev/booking-api-django/venv/lib/python3.8/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/p7chkn/Dev/booking-api-django/bookings/views_admin.py", line 72, in get
    response = serializer.get_statistic()
  File "/home/p7chkn/Dev/booking-api-django/bookings/serializers_admin.py", line 376, in get_statistic
    month_num = int(strptime(month, '%B').tm_mon)
  File "/usr/lib/python3.8/_strptime.py", line 562, in _strptime_time
    tt = _strptime(data_string, format)[0]
  File "/usr/lib/python3.8/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '12' does not match format '%B'
[27/May/2021 14:03:28,760] [31m[0m
[27/May/2021 14:03:28,760] [31mRequest on GET /admin/booking/employee_stats?month=12&year=2001 ended with code: 500[0m
[27/May/2021 14:03:28,760] [31mUser: fe87620c-5e80-4a1c-9c30-c4681387483a, Account: 7689fea5-32e6-4b36-a353-e152e8eb814d[0m
[27/May/2021 14:03:28,760] [31mRequest details:[0m
[27/May/2021 14:03:28,761] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.0', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '9daf256b-53e9-4ffc-a1a8-e1b307a673af', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[27/May/2021 14:03:28,761] [31mResponse details:[0m
[27/May/2021 14:03:28,762] [31mUsed tables: groups_group, users_account, users_account_groups, users_user[0m
[27/May/2021 14:04:26,579] [31m[0m
[27/May/2021 14:04:26,579] [31mRequest on GET /admin/booking/employee_stats?month=September&year=2001 ended with code: 404[0m
[27/May/2021 14:04:26,579] [31mUser: fe87620c-5e80-4a1c-9c30-c4681387483a, Account: 7689fea5-32e6-4b36-a353-e152e8eb814d[0m
[27/May/2021 14:04:26,579] [31mRequest details:[0m
[27/May/2021 14:04:26,580] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.0', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'ce0f2205-b805-40f5-8505-f81bf7aa3786', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[27/May/2021 14:04:26,580] [31mResponse details:[0m
[27/May/2021 14:04:26,581] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '14')}[0m
[27/May/2021 14:04:26,581] [31m{"message":""}[0m
[27/May/2021 14:04:26,581] [31mUsed tables: groups_group, users_account, users_account_groups, users_user[0m
[27/May/2021 14:05:19,972] [31m[0m
[27/May/2021 14:05:19,973] [31mRequest on GET /admin/booking/employee_stats?month=September&year=2001 ended with code: 404[0m
[27/May/2021 14:05:19,973] [31mUser: fe87620c-5e80-4a1c-9c30-c4681387483a, Account: 7689fea5-32e6-4b36-a353-e152e8eb814d[0m
[27/May/2021 14:05:19,973] [31mRequest details:[0m
[27/May/2021 14:05:19,974] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.0', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '52b5a91d-a668-488e-a840-04c9f7e9c715', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[27/May/2021 14:05:19,975] [31mResponse details:[0m
[27/May/2021 14:05:19,975] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '14')}[0m
[27/May/2021 14:05:19,975] [31m{"message":""}[0m
[27/May/2021 14:05:19,976] [31mUsed tables: groups_group, users_account, users_user, users_account_groups[0m
[27/May/2021 14:05:44,044] [31m[0m
[27/May/2021 14:05:44,044] [31mRequest on GET /admin/booking/employee_stats?month=September&year=2001 ended with code: 404[0m
[27/May/2021 14:05:44,044] [31mUser: fe87620c-5e80-4a1c-9c30-c4681387483a, Account: 7689fea5-32e6-4b36-a353-e152e8eb814d[0m
[27/May/2021 14:05:44,044] [31mRequest details:[0m
[27/May/2021 14:05:44,045] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.0', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': '780cb440-2ec7-4396-90eb-ace759ce726a', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[27/May/2021 14:05:44,046] [31mResponse details:[0m
[27/May/2021 14:05:44,047] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '14')}[0m
[27/May/2021 14:05:44,047] [31m{"message":""}[0m
[27/May/2021 14:05:44,048] [31mUsed tables: users_user, users_account_groups, groups_group, users_account[0m
[27/May/2021 14:06:35,492] [31m[0m
[27/May/2021 14:06:35,493] [31mRequest on GET /book/employee_stats?month=September&year=2001 ended with code: 404[0m
[27/May/2021 14:06:35,493] [31mUser: fe87620c-5e80-4a1c-9c30-c4681387483a, Account: 7689fea5-32e6-4b36-a353-e152e8eb814d[0m
[27/May/2021 14:06:35,493] [31mRequest details:[0m
[27/May/2021 14:06:35,494] [31m{'HTTP_AUTHORIZATION': '*****', 'HTTP_USER_AGENT': 'PostmanRuntime/7.28.0', 'HTTP_ACCEPT': '*/*', 'HTTP_CACHE_CONTROL': 'no-cache', 'HTTP_POSTMAN_TOKEN': 'f9e7905b-5e38-4928-b99c-07255af53e0f', 'HTTP_HOST': '127.0.0.1:8000', 'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br', 'HTTP_CONNECTION': 'keep-alive'}[0m
[27/May/2021 14:06:35,494] [31mResponse details:[0m
[27/May/2021 14:06:35,495] [31m{'content-type': ('Content-Type', 'application/json; charset=utf-8'), 'vary': ('Vary', 'Accept, Origin'), 'allow': ('Allow', 'GET, HEAD, OPTIONS'), 'x-frame-options': ('X-Frame-Options', 'DENY'), 'content-length': ('Content-Length', '16')}[0m
[27/May/2021 14:06:35,495] [31m"Data not found"[0m
[27/May/2021 14:06:35,495] [31mUsed tables: users_user, users_account_groups, groups_group, users_account[0m
[27/May/2021 14:07:04,910] [32m[0m
[27/May/2021 14:07:04,910] [32mRequest on GET /book/employee_stats?month=May&year=2021 ended with code: 201[0m
[27/May/2021 14:07:04,911] [32mUser: fe87620c-5e80-4a1c-9c30-c4681387483a, Account: 7689fea5-32e6-4b36-a353-e152e8eb814d[0m
[27/May/2021 14:07:04,911] [32mUsed tables: users_user, users_account_groups, groups_group, users_account[0m
[27/May/2021 14:07:22,607] [32m[0m
[27/May/2021 14:07:22,607] [32mRequest on GET /admin/booking/employee_stats?month=May&year=2021 ended with code: 200[0m
[27/May/2021 14:07:22,607] [32mUser: fe87620c-5e80-4a1c-9c30-c4681387483a, Account: 7689fea5-32e6-4b36-a353-e152e8eb814d[0m
[27/May/2021 14:07:22,608] [32mUsed tables: users_user, users_account_groups, groups_group, users_account[0m
[27/May/2021 14:10:26,213] [32m[0m
[27/May/2021 14:10:26,214] [32mRequest on GET /admin/booking/employee_stats?month=May&year=2021 ended with code: 200[0m
[27/May/2021 14:10:26,214] [32mUser: fe87620c-5e80-4a1c-9c30-c4681387483a, Account: 7689fea5-32e6-4b36-a353-e152e8eb814d[0m
[27/May/2021 14:10:26,215] [32mUsed tables: groups_group, users_user, users_account_groups, users_account[0m
[27/May/2021 14:10:44,676] [32m[0m
[27/May/2021 14:10:44,676] [32mRequest on GET /book/employee_stats?month=May&year=2021 ended with code: 201[0m
[27/May/2021 14:10:44,676] [32mUser: fe87620c-5e80-4a1c-9c30-c4681387483a, Account: 7689fea5-32e6-4b36-a353-e152e8eb814d[0m
[27/May/2021 14:10:44,677] [32mUsed tables: groups_group, users_user, users_account_groups, users_account[0m
[27/May/2021 14:11:26,270] [32m[0m
[27/May/2021 14:11:26,270] [32mRequest on GET /admin/booking/employee_stats?month=May&year=2021 ended with code: 200[0m
[27/May/2021 14:11:26,270] [32mUser: fe87620c-5e80-4a1c-9c30-c4681387483a, Account: 7689fea5-32e6-4b36-a353-e152e8eb814d[0m
[27/May/2021 14:11:26,271] [32mUsed tables: groups_group, users_user, users_account_groups, users_account[0m
